# Source: https://github.com/boostorg/hana/blob/master/.travis.yml

# Use C++ build environment.
language: cpp

# Protobuf requires g++ (see https://github.com/google/protobuf/blob/master/src/README.md)
compiler:
    - gcc

dist: xenial

addons:
    apt:
        packages:
            - cmake
            - libprotobuf-dev
            - protobuf-compiler
            - qtbase5-dev
            - libzmq3-dev

# Run the build script.
script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
